### ISSUE TITLE
Cache dir should be done as a argument.

### ISSUE THREAD

**Issue by kennedyshead** [kivy-garden/garden.mapview#28]
In iOS you have no permission to write to install directory. If mapview could be initialized with cache_dir as argument.

```
 IOError: [Errno 1] Operation not permitted: 'cache/26a7511794_19_281901_367007.png'
```

**Comment by zoltan-fedor** [comment]
Hi @kennedyshead ,
Sorry for the question, but after setting my custom cache-dir (subdirectory of the app) on iOS I still cannot write the cache *.png images into it.
What directory did you set, alias what directory an iOS app with mapview is allowed to write into? 
Thanks!

**Comment by zoltan-fedor** [comment]
Figured it out, it should be /Library/Caches based on https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW28
