### ISSUE TITLE
mapview android phone crashes after adding library kivy.garden.mapview

### ISSUE THREAD

**Issue by pysebb** [kivy-garden/garden.mapview#3]
I'm developing an application, which uses kivy garden map view. After importing library "kivy.garden.mapview" to my "main.py" file, I deploy my application on my Samsung Galaxy S5 with 4.2.2 android installed. When I try to run the app, after deployment - my phone crashes, and it reboots automaticly. Unfortunetely I'm unable to post a logcat from that crash. After reboot it is possible for me run the app (the loadscreen appears), after few seconds it also crashes.
Bellow I post my logcat which is saying that my urllib3 is missing. But the fun thing is, I've imported requests to my buildozer.spec (I`ve even tried to import urllib3 also).

http://pastebin.com/rcy31LeU

**Comment by tito** [comment]
I was having the issue (not reboot) about urllib3. It appear that requests is actually messing up with the import system. The real issue is urllib3 cannot import _ssl, so it fail.

Ie: you need to add openssl into the requirements in your buildozer.spec
