### ISSUE TITLE
Dark rectangles when connecting to a big monitor!

### ISSUE THREAD

**Issue by ehsanaerabi** [kivy-garden/garden.mapview#31]
When I connect the Raspberry Pi board to a very big TV, I see dark rectangles inside MapView.

**Comment by tito** [comment]
I have no idea what you're talking about :(

What are the "big" rectangle? No picture/screenshot?
Dark rectangle = black? Is it the background?
You may also just have not enough memory to run it therefor you're seeing black texture?

Please reopen if you have actual code/more information/screenshot about the behavior.
