### ISSUE TITLE
Start apk issue

### ISSUE THREAD

**Issue by freemansgithub** [kivy-garden/garden.mapview#34]
I have built apk including MapView widget successfully using buildozer with reqs futures and openssl. But after installing on device app doesn't run without any messages. Do you have successfull exp ?

**Comment by Esubalew24** [comment]
I have also same problem. I have tried it with kivy launcher and it crashes automatically. The problem is with the MapView, other program codes work perfectly. Anyone knows how to solve this problem?

**Comment by tito** [comment]
If you don't provide logs, you can't know what's going on. Neither we can help here :)
