### ISSUE TITLE
Does not run on the device

### ISSUE THREAD

**Issue by rickdps** [kivy-garden/garden.mapview#39]
Hi. 

Please, somebody help me. I have been trying to get the project's first page "Usage" example to work on the device but it crashes when launching. On the computer it works fine.  

Appreciate any help.

**Comment by tito** [comment]
You can't provide device logs, we can't help to fix the issue.

**Comment by tito** [comment]
And we don't know what "device" it is.
If you talk about Android or iOS, it does work, i'm using it for various apps on both platforms.
