### ISSUE TITLE
AttributeError: 'MapView' object has no attribute '_disabled_count'

### ISSUE THREAD

**Issue by paulemurray** [kivy-garden/garden.mapview#42]
`   File "/usr/lib/python2.7/site-packages/kivy/uix/widget.py", line 534, in add_widget
     widget._disabled_count = self._disabled_count
 AttributeError: 'MapView' object has no attribute '_disabled_count'
`
Using newest Kivy dev version, I haven;t been able to get any other versions working so I'm not sure if it's a Kivy dev thing or a MapView thing

**Comment by whitelynx** [comment]
~Given where that error is happening (`kivy/uix/widget.py`), that looks like an issue with Kivy itself, not with the map view. You might want to open an issue on the main project instead.~

Actually, that looks like it could be an issue with a mismatch between `kivy` and `garden.mapview`... but I'm not sure exactly how this is happening; I'm running this on Kivy `master` and I'm not having this problem. What specific versions of each are you using?

**Comment by Lauszus** [comment]
This was solved in https://github.com/kivy-garden/garden.mapview/pull/41.
