### ISSUE TITLE
Dynamically add content (multiple widgets) in a map marker popup.

### ISSUE THREAD

**Issue by kiok46** [kivy-garden/garden.mapview#5]
This link from Stackoverflow ( http://stackoverflow.com/questions/30862740/create-popup-in-mapmarkerpopup-on-the-python-sidenot-in-kv-file-in-kivy-garden ) is the real issue but just in case the link is removed I will post the problem here.
From source code it seems like it's not possible to add content dynamically from python side in the map marker popup.

```
mapview.add_marker(MapMarkerPopup(lat=-33.8670512,lon=151.206, content=???))
```

while In `Popup` from `kivy.uix.popup` we can add content to it.

```
Popup(title='Test popup', content=Label(text='Hello world'),
    size_hint=(None, None), size=(400, 400))
```

Suggestions are welcome.

**Comment by matham** [comment]
This issue doesn't belong in Kivy, I think, but in the relevant garden repo.

**Comment by kiok46** [comment]
@matham  I think, that's what I did :)

**Comment by kiok46** [comment]
Just one look into the source code solved this.

`a = Bubble()`
`mapview.add_marker(MapMarkerPopup(lat=-33.8670512,lon=151.206, placeholder= a))`

But adding it dynamically won't add the new bubble on top of the marker  For this maybe `set_marker_position` method in the MapMarkerLayer needs to be changed but I am not sure about it.
But as of now this issue is solved.
Closing it.
