### ISSUE TITLE
insert_marker incompatible with Python 3

### ISSUE THREAD

**Issue by alfajet** [kivy-garden/garden.mapview#55]
In https://github.com/kivy-garden/garden.mapview/blob/master/mapview/view.py#L206
lambda (i, m) is not  a valid syntax in Python 3
as suggested here: https://stackoverflow.com/a/21893097
I have modified my local copy of this function as follow:
```python
    def insert_marker(self, marker, **kwargs):
        if self.order_marker_by_latitude:
            i_m = (i, m)
            before = list(takewhile(
                lambda i_m: i[1].lat < marker.lat,
                enumerate(self.children)
            ))
            if before:
                kwargs['index'] = before[-1][0] + 1

        super(MarkerMapLayer, self).add_widget(marker, **kwargs)
```
the variable i doesn't seem to be used, perhaps this could be further simplified.

**Comment by ghost** [comment]
```python
    def insert_marker(self, marker, **kwargs):
        if self.order_marker_by_latitude:
            before = list(takewhile(
                lambda i_m: i_m[1].lat < marker.lat,
                enumerate(self.children)
            ))
            if before:
                kwargs['index'] = before[-1][0] + 1

        super(MarkerMapLayer, self).add_widget(marker, **kwargs)
```

this should do it

**Comment by pythonpapadotin** [comment]
> 
> 
> ```python
>     def insert_marker(self, marker, **kwargs):
>         if self.order_marker_by_latitude:
>             before = list(takewhile(
>                 lambda i_m: i_m[1].lat < marker.lat,
>                 enumerate(self.children)
>             ))
>             if before:
>                 kwargs['index'] = before[-1][0] + 1
> 
>         super(MarkerMapLayer, self).add_widget(marker, **kwargs)
> ```
> 
> this should do it

Thank You Yakult. It really worked.

**Comment by AndreMiras** [comment]
I think this got fixed in https://github.com/kivy-garden/garden.mapview/pull/66
