### ISSUE TITLE
PyInstaller does not include the mapview package.

### ISSUE THREAD

**Issue by pythonpapadotin** [kivy-garden/garden.mapview#59]
Python Version: 3.6.7(Anaconda Environment)
Kivy Version: 1.10.1

So I installed mapview with the command `garden install mapview` and my python file easily detects it and runs it.But when I make exe with PyInstaller it showed the following error `ModuleNotFoundError: No module named garden.mapview`

I somehow found a solution to install all garden things by adding `--kivy` in the end.

I used matplotlib of garden with command `garden install matplotlib --kivy` and it works after making exe with PyInstaller using method shown here [https://kivy.org/doc/stable/guide/packaging-windows.html](url)

But when I installed mapview with the command `garden install mapview --kivy` which makes it appear in site-packages of my Anaconda Environment, it shows following error- ` ModuleNotFoundError: No module named 'mapview.types'`

So it seems like adding `--kivy` improved the situation but didn't completely solved it.
So how to do it?Any workaounds will also be appreciated.

**Comment by ocobacho** [comment]
I don't know about Pyinstaller but I have use mapview by copying the mapview folder in the root of the project. Hope it helps.

**Comment by pythonpapadotin** [comment]
> 
> 
> I don't know about Pyinstaller but I have use mapview by copying the mapview folder in the root of the project. Hope it helps.

It was a long time ago that I had that Problem, but I think I solved it the same way by copying the stuff to my project directory.
