### ISSUE TITLE
Tilt and rotate maps

### ISSUE THREAD

**Issue by EdwinCO** [kivy-garden/garden.mapview#9]
Hello,
I'm using the network but  I need some control to tilt or rotate the map, it's possible to do this?

**Comment by tito** [comment]
There is no support for tilt/rotation yet. Dunno if it can be easily achievable, but rotating a bitmap will also rotate the text, which will be completely useless.

If a vector tiles was done, it may be feasible.

But for now, it's not in the roadmap. If anyone want to tackle this one, please contribute :)
